blog/urls.py
from django.conf.urls.defaults import *
from django.views.generic import ListView, DetailView, TemplateView
from models import Post
from forms import PostForm
from views import CreateView, UpdateView, DeleteView, FilteredListView, FilteredDetailView, admin_home
from django.contrib.auth.decorators import login_required

# Django 1.3 doesn't get to be lazy!
try:
	from django.core.urlresolvers import reverse_lazy
except ImportError:
	from django.core.urlresolvers import reverse
	from django.utils.functional import lazy
	reverse_lazy = lambda x: lazy(reverse, str)(x)


urlpatterns = patterns('',
	# Somehow I don't like django contrib admin
	# Pluse it feels bit like cheating, so..
	url(r'^admin/post/$', login_required(ListView.as_view(
		paginate_by=10,
		model=Post
		)), name="post-list"
	),
	url(r'^admin/post/createform/$', login_required(CreateView.as_view(
		model=Post,
		form_class=PostForm,
		)), name="post-createform"
	),
	url(r'^admin/post/(?P<pk>\d+)/editform/$', login_required(UpdateView.as_view(
		model=Post,
		form_class=PostForm,
		)), name="post-editform"
	),
	url(r'^admin/post/(?P<pk>\d+)/deleteform/$', login_required(DeleteView.as_view(
		model=Post
		)), name="post-deleteform"
	),
	url(r'^admin/$', admin_home, name="admin"),
	url(r'^$', FilteredListView.as_view(
		paginate_by=5,
		model=Post,
		template_name="blog/index.html"
		), name="index"
	),
	url(r'^(?P<slug>[a-z0-9\-]+)/$', FilteredDetailView.as_view(
		model=Post,
		slug_field='permalink',
		template_name="blog/post.html"
		), name="post"
	),
	url('^login/error/$', TemplateView.as_view(
		template_name="login-error.html"
	)),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
	url('^_ah/warmup/$', 'djangoappengine.views.warmup'),
	url('', include('blog.urls', namespace='blog')),
	# url(r'^account/', include('account.urls', namespace='account')),
	url('^account/', include('registration.backends.default.urls')),
	url('^account/', include('django.contrib.auth.urls')),
	url('', include('social_auth.urls')),
)

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
	name = models.CharField(max_length=50)


class Post(models.Model):
	VISIBILITY_OPTIONS = (
		(0, 'Private'),
		(1, 'Registered Users only'),
		(2, 'Public')
	)
	title = models.CharField(max_length=200)
	date_created = models.DateTimeField(auto_now_add=True)
	date_modified = models.DateTimeField(auto_now=True)
	visibility = models.PositiveSmallIntegerField(choices=VISIBILITY_OPTIONS, default=0)
	text = models.TextField()
	author = models.ForeignKey(User)
	permalink = models.CharField(max_length=200, unique=True)
	class Meta:
		ordering = ['-date_created']


class Tag(models.Model):
	article = models.ForeignKey(Post)
	title = models.CharField(max_length=200)

blog/forms.py
from django.forms import ModelForm
from models import Post
from django import forms

# from django.forms import widgets

# from django.conf import settings
# from django.template.loader import render_to_string
# from django.utils.safestring import mark_safe


# class MarkdownWidget(widgets.TextInput):
# 	class Media:
# 		js = ('Markdown.Converter.js', 'Markdown.Sanitizer.js', 'Markdown.Editor.js')

# 	def render(self, name, value, attrs=None):
# 		return mark_safe(render_to_string('_widgets/markdown.html', {
# 			"name": name,
# 			"value": value,
# 			"STATIC_URL": settings.STATIC_URL  # middleware won't work here
# 		}))


class PostForm(ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'permalink', 'visibility', 'text')
		widgets = {
			'permalink': forms.TextInput(attrs={
				'data-provide': 'permalink',
				'data-based-on': 'title'
			}),
			'text': forms.Textarea(attrs={
				'data-provide': 'markdown',
			})
		}

blog/views.py
from django.views.generic import *
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from social_auth import backends
# from django.db.models import Q


class FilteredListView(ListView):
	def get_queryset(self):
		if(self.request.user.is_authenticated()):
			# Sadly no support for OR filters in appengine :(
			# query = Q(visibility__in=[1, 2]) | Q(visibility=0, author=self.request.user)
			# nope
			# self.model.objects.all().exclude(~Q(author=self.request.user), visibility=0)
			return self.model.objects.filter(visibility__in=[1, 2])
		else:
			return self.model.objects.filter(visibility=2)


class FilteredDetailView(DetailView):
	def get_object(self):
		user = self.request.user
		object = super(FilteredDetailView, self).get_object()
		if(object.visibility == 2):
			return object
		if(user.is_authenticated and object.visibility == 1):
			return object
		if(user.is_authenticated and object.visibility == 0 and object.author == user):
			return object
		raise Http404(_(u"No %(verbose_name)s found matching the query")
			% {'verbose_name': queryset.model._meta.verbose_name})


class SuccessUrlMixin(object):
	def get_success_url(self):
		if('postaction' in self.request.POST and self.request.POST['postaction'] == "Save"):
			return reverse("%s:%s-editform" % ("blog", self.model.__name__.lower()), kwargs={"pk": self.object.id})
		else:
			return reverse("%s:%s-list" % ("blog", self.model.__name__.lower()))


class OwnershipMixin(object):
	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.author = self.request.user
		return super(OwnershipMixin, self).form_valid(form)


class CreateView(SuccessUrlMixin, OwnershipMixin, CreateView):
	pass


class UpdateView(SuccessUrlMixin, UpdateView):
	pass


class DeleteView(SuccessUrlMixin, DeleteView):
	pass


@login_required
def admin_home(request):
	potential_providers = backends.get_backends().keys()
	for social in request.user.social_auth.all():
		if social.provider in potential_providers:
			potential_providers = [x for x in potential_providers if x != social.provider]

	return render(request, 'admin_home.html', {
		'potential_providers': potential_providers
	})

templates/blog/index.html
{% extends "base.html" %}
{% block content %}
	{% for post in object_list %}
		{% include "blog/_partials/post.html" %}
	{% endfor %}

{% if is_paginated %}
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span4 meta">
				<h2>Want more?</h2>
				<ul>
					{% if page_obj.has_previous %}
						<li>
							<a href="?page={{ page_obj.previous_page_number }}">
								Newer Posts
								<span class="accent-color icon icon-arrow-left"></span>
							</a>
						</li>
					{% endif %}
					{% if page_obj.has_next %}
					<li>
						<a href="?page={{ page_obj.next_page_number }}">
							Older Posts
							<span class="accent-color icon icon-arrow-right"></span>
						</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</div>
{% endif %}

{% endblock %}
{% block post-content %}
<div class="container-fluid">
	<div class="row-fluid">
		{% include "blog/_partials/post-content-menu.html" %}
	</div>
</div>
{% endblock %}

templates/blog/post.html
{% extends "base.html" %}
{% block content %}
	{% include "blog/_partials/post.html" %}
{% endblock %}
{% block post-content %}
<div class="container-fluid">
	<div class="row-fluid">
		{% include "blog/_partials/post-content-menu.html" %}
	</div>
</div>
{% endblock %}

templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
	<div class="alert alert-warning">
		 <strong>Please Confirm.</strong> You're about to remove post <strong>{{ post.title }}</strong> by <strong>{{ post.author }}</strong>. Are you sure you want to continue? This operation cannot be reverted!
		 <form method="post" action="" class="right">
		 	{% csrf_token %}
		 	<a href="{% url blog:post-list %}" class="btn">Cancel</a>
		 	<button class="btn btn-danger" type="submit">Delete</button>
		 </form>
	</div>
</div>

{% endblock %}

templates/blog/post_form.html
{% extends "admin.html" %}
{% block admin-content %}
<form method="post" action="" class="form-horizontal">
	{% csrf_token %}
	{% if form.non_field_errors %}
		<div class="alert alert-error">
			{{ form.non_field_errors }}
		</div>
	{% endif %}
{% for field in form %}
	{% if field.errors %}
		<div class="alert alert-error">
			{{ field.errors }}
		</div>
	{% endif %}
	<label class="control-label" for="id_{{ field.html_name }}">
		{{ field.label }}
	</label>
	 <div class="controls">
	  {{ field }}
	</div>
{% endfor %}

<div class="control-group">
	<div class="controls">
		<button type="submit" class="btn btn-primary" name="postaction" value="Save" >Save</button>
		<button type="submit" class="btn btn-primary" name="postaction" value="Save &amp; Back" >Save &amp; Back</button>
		<a href="{% url blog:post-list %}" class="btn btn-warning">Cancel</a>
	</div>
  </div>
</form>
{% endblock %}

templates/blog/post_list.html
{% extends "admin.html" %}
{% block admin-content %}
<table class="table table-striped">
	<thead>
		<tr>
			<th>Title</th>
			<th>Author</th>
			<th>Visibility</th>
			<th>Date Created</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for post in object_list %}
		<tr>
			<td>{{ post.title }}</td>
			<td>{{ post.author }}</td>
			<td>{{ post.get_visibility_display }}</td>
			<td>{{ post.date_created }}</td>
			<td>
				<a href="{% url blog:post slug=post.permalink %}" class="btn btn-primary">
					<span class="icon-search"></span>
				</a>
				<a href="{% url blog:post-editform pk=post.id %}" class="btn btn-primary">
					<span class="icon-pencil"></span>
				</a>
				<a href="{% url blog:post-deleteform pk=post.id %}" class="btn btn-danger">
					<span class="icon-remove"></span>
				</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% if is_paginated %}
<div class="pagination">
	<ul>
		{% for page in page_obj.paginator.page_range %}
			{% if page == page_obj.number %}
				<li class="active"><a href="#">{{ page }}</a></li>
			{% else %}
				<li><a href="?page={{ page }}">{{ page }} </a></li>
			{% endif %}
		{% endfor %}
	</ul>
</div>
{% endif %}

{% endblock %}